import type {Metadata} from "next";
import {Cormorant_Garamond, EB_Garamond} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";

const font = Cormorant_Garamond({
    variable: "--font-sans",
    subsets: ["latin"],
});

const fontEb = EB_Garamond({
    variable: "--font-sans-eb",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", font.variable, fontEb.variable, "font-sans")}
        >
        <body className="min-h-full flex flex-col leather">
        {children}
        </body>
        </html>
    );
}
